name: Hello Actions

on: [push, workflow_dispatch]

jobs:
  # This section adds a job named "say-hello"
  say-hello:
    runs-on: ubuntu-latest
    steps:
      # This section adds a run step
      - name: Print a greeting
        run: echo "Hello, GitHub Actions!"
